export default {
    users:[
        {
            name:'Vladistas',
            posts:[
                {
                    text:'HELLO!',
                    tags:[
                        {
                            name:'Beauty'
                        },
                        {
                            name:'Healthstone'
                        },
                    ],
                },
                {
                    text:'I whant to say hello to your batya!!!1',
                    tags:[
                        {
                            name:'BIBBLETUMP'
                        },
                        {
                            name:'Healthstone'
                        },
                    ],
                },
            ],
        },
        {
            name:'Vladistas2',
            posts:[
                {
                    text:'I whant to say hello to your batya!!!1',
                    tags:[
                        {
                            name:'BIBBLETUMP'
                        },
                        {
                            name:'Healthstone'
                        },
                    ],
                },
            ],
        },
    ]
} 